name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  auto_route: ^10.0.1
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^13.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: 5.6.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  shared_preferences: ^2.3.0
  shimmer: ^3.0.0
  get: ^4.6.6
  intl: ^0.19.0
  http: ^1.2.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  android_alarm_manager_plus: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/Facebook.png
    - lib/assets/Home.png
    - lib/assets/Analysis.png
    - lib/assets/Google.png
    - lib/assets/Categories.png
    - lib/assets/Transactions.png
    - lib/assets/Profile.png
    - lib/assets/Expense.png
    - lib/assets/Income.png
    - lib/assets/Notification.png
    - lib/assets/Car.png
    - lib/assets/Food.png
    - lib/assets/Medicine.png
    - lib/assets/Gift.png
    - lib/assets/Saving.png
    - lib/assets/More.png
    - lib/assets/Entertainment.png
    - lib/assets/Salary.png
    - lib/assets/Pantry.png
    - lib/assets/Check.png
    - lib/assets/Rent.png
    - lib/assets/Search.png
    - lib/assets/Transport.png
    - lib/assets/Groceries.png
    - lib/assets/Security.png
    - lib/assets/Logout.png
    - lib/assets/Settings.png
    - lib/assets/Help.png
    - lib/assets/profile_image.png
    - lib/assets/Travel.png
    - lib/assets/Fingerprint.png
    - lib/assets/New House.png
    - lib/assets/Wedding.png
  uses-material-design: true